### ISSUE TITLE
KEYPOD: Show ID/webID of logged-in user

### ISSUE THREAD

**Issue by cdawei** [anusii/keypod#101] opened 2024-05-23 01:24 UTC
Anushka suggested that we could show the ID/webID of logged-in user in the `keypod` app, as is commonly done in many apps.

Also add an indicator if a user has not logged in.

For example, at the top-/bottom-left corner, show the user's webID if logged in, or display "Not logged in".

**Comment by gjwgit** [comment] 2024-05-24 06:21
I think this is a duplicate of #97. If so then close this one.

**Comment by cdawei** [comment] 2024-05-24 07:17
Showing user's webID in the About dialog is one option to fix this issue, but that approach is not always viable (e.g. I imagine a user can click the `Continue` button and then the About dialog, in this case, the user has not yet provided his/her webID).

Updated the issue description to make the task clearer.

**Comment by gjwgit** [comment] 2024-05-24 09:51
Thanks for the clarification. Yes that makes sense and is needed. I am never sure and it's good to have this as the standard thing to do.

**Comment by cdawei** [comment] 2024-06-18 01:38
If logged in
![Image](https://github.com/anusii/keypod/assets/13044715/41bb5dd0-8005-45e1-8d73-caea4ce49bba)

If not logged in, or clicking `Forget Remote Solid Server Login Info` button after logging in.
![Image](https://github.com/anusii/keypod/assets/13044715/3ef9d52e-a6aa-40dc-a245-9745070b75e9)

**Closed as completed** 2024-06-21 01:30 UTC
